apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: demo-environment
spec:
  containers:
  - name: secret-container
    image: busybox
    command: ["sleep", "3600"]
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
