---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: jaimin
  become: false
  tasks:

    - name: Install Python Docker SDK
      apt:
        name: python3-docker
        state: present
      become: false

    - name: Pull Docker Image
      docker_image:
        name: "enum3rat3/calculator:v1"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name calculator enum3rat3/calculator:v1
