pipeline {
	agent any
	
	stages {
		stage('checkout') {
			steps{
				script{
					git branch: 'main', url:'https://github.com/enum3rat3/Software-Production-Engineering.git'
				}
			}
		}

		stage('Build Docker Image') {
			steps{
				script{
					dockerImage = docker.build('enum3rat3/calculator:v1', 'Calculator/')
				}
			}
		}
		
		stage('Push Docker Image') {
			steps{
				script{
					docker.withRegistry('', 'docker-hub-creds') {
						dockerImage.push()
                    }
				}
			}
		}

		stage('Deployment using Ansible')
		{
			steps{
				sh 'ansible-playbook Calculator/deploy.yml -i Calculator/inventory -vvvv'
			}
		}
	}
}