apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
  namespace: demo-environment
spec:
  containers:
  - name: configmap-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: config-volume
      mountPath: "/etc/config"
  volumes:
  - name: config-volume
    configMap:
      name: app-config
