apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: curl-container
    image: curlimages/curl:latest
    command: ["sh", "-c", "while true; do curl backend-service:5678; sleep 5; done"]
