apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: demo-environment
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
